-- Create Products Table for Oottam
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    short_description VARCHAR(200) NOT NULL,
    price FLOAT NOT NULL,
    original_price FLOAT,
    type VARCHAR(50) NOT NULL,
    flavor VARCHAR(50) NOT NULL,
    image VARCHAR(100) NOT NULL,
    ingredients TEXT NOT NULL,
    how_to_use TEXT NOT NULL,
    use_cases TEXT NOT NULL,
    benefits TEXT NOT NULL,
    in_stock BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Sample Products
INSERT INTO products (name, slug, description, short_description, price, original_price, type, flavor, image, ingredients, how_to_use, use_cases, benefits) VALUES
(
    'Multipurpose Flour - Original',
    'multipurpose-flour-original',
    'Our signature multipurpose flour crafted from the finest wheat, milled using traditional methods to preserve natural nutrition. Perfect for everyday meals that your family will love.',
    'Our signature flour for everyday meals',
    249,
    299,
    'multipurpose',
    'original',
    'flour-original',
    'Whole Wheat Flour (90%), Rice Flour (5%), Bengal Gram Flour (5%)\n\nNo preservatives. No artificial additives. 100% natural.',
    '1. Take required amount of flour\n2. Add water gradually\n3. Knead to desired consistency\n4. Use for roti, dosa, porridge, or snacks',
    'Roti|Dosa|Porridge|Snacks|Quick Meals',
    'High fiber|Multiple use cases|Quick preparation|Traditional taste'
),
(
    'Multipurpose Flour - Multigrain',
    'multipurpose-flour-multigrain',
    'A powerhouse of nutrition combining six grains. Rich in fiber and protein, this multigrain flour supports digestive health while delivering authentic taste.',
    'Power-packed nutrition from six grains',
    299,
    349,
    'multipurpose',
    'multigrain',
    'flour-multigrain',
    'Wheat Flour (40%), Ragi Flour (15%), Jowar Flour (15%), Bajra Flour (10%), Rice Flour (10%), Chana Flour (10%)\n\nNo preservatives. No artificial additives.',
    '1. Mix flour well\n2. Add water as needed\n3. Knead into soft dough\n4. Cook as usual',
    'Roti|Dosa|Uttapam|Snacks|Breakfast',
    'High protein|High fiber|6-grain nutrition|Heart healthy'
),
(
    'Ragi Flour - Instant',
    'ragi-flour-instant',
    'Nature''s superfood in its purest form. Ragi is rich in calcium and iron, making it perfect for growing children and health-conscious adults.',
    'Nutrient-rich superfood flour',
    179,
    NULL,
    'instant',
    'ragi',
    'flour-ragi',
    'Organic Finger Millet (Ragi) Flour (100%)\n\nNo preservatives. No artificial additives. Single ingredient.',
    '1. Mix 2-3 tbsp with water or milk\n2. Boil for 5 minutes\n3. Add jaggery for sweetness\n4. Serve warm',
    'Porridge|Roti|Breakfast|Health Drink|Desserts',
    'High calcium|High iron|Natural energy|Gluten-free'
),
(
    'Rice Flour - Fine',
    'rice-flour-fine',
    'Stone-ground fine rice flour ideal for traditional recipes like paniyaram, neer dosa, and crispy snacks. Light, easy to digest, and naturally gluten-free.',
    'Traditional recipes made easy',
    169,
    199,
    'multipurpose',
    'rice',
    'flour-rice',
    'Organic Rice Flour (100%)\n\nNo preservatives. No artificial additives. Single ingredient.',
    '1. Mix with water to desired consistency\n2. Add salt and spices\n3. Ferment if needed\n4. Cook as per recipe',
    'Dosa|Snacks|Fryums|desserts|Batters',
    'Gluten-free|Light texture|Easy digest|Low allergy'
),
(
    'Kitchen Special Combo',
    'kitchen-special-combo',
    'The complete kitchen solution. Four essential flours in one pack - Original, Multigrain, Ragi, and Rice. Everything you need for a week of healthy meals.',
    'Four flours. Endless possibilities.',
    699,
    849,
    'combo',
    'original',
    'flour-combo',
    'Set includes: Original Flour (1kg), Multigrain Flour (500g), Ragi Flour (500g), Rice Flour (500g)\n\nNo preservatives. No artificial additives.',
    'Use each flour according to its specific instructions. Mix and match for creative recipes.',
    'All recipes|Variety meals|Experiments|Gifts',
    'Best value|4-in-1|Variety|Perfect for families'
),
(
    'Breakfast Mix - Instant',
    'breakfast-mix-instant',
    'Start your morning right with our ready-to-cook breakfast mix. Just add water and cook for nutritious dosas or pancakes in under 5 minutes.',
    'Healthy breakfast in 5 minutes',
    189,
    NULL,
    'instant',
    'original',
    'flour-breakfast',
    'Rice Flour (60%), Urad Dal Flour (20%), Wheat Flour (15%), Salt, Fenugreek (5%)\n\nNo preservatives. No artificial additives.',
    '1. Mix 1 cup flour with 1 cup water\n2. Let rest for 5 minutes\n3. Cook on hot tawa like regular dosa\n4. Serve with favorite sides',
    'Dosa|Pancakes|Upma|Breakfast|Snacks',
    'Quick prep|High protein|Healthy start|Zero effort'
);